name: e_commerce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/ui_design.jpg
    - assets/images/online_shop.jpg
    - assets/images/shop3.jpg
    - assets/images/shop2.jpg
    - assets/images/logo2.png
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/verify_email.png
    - assets/images/success.jpg
    - assets/images/password_reset.png
    - assets/images/sneakers.png
    - assets/images/sport-shoe.png
    - assets/images/slider.jpg
    - assets/images/slider1.jpg
    - assets/images/slider2.jpg
    - assets/images/product.jpg
    - assets/images/dressmaker.png
    - assets/logos/e_logo.png





